#!/bin/sh
### BEGIN INIT INFO
# Provides:          lighttpd
# Required-Start:    networking
# Required-Stop:     networking
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the lighttpd web server.
### END INIT INFO


PATH=/sbin:/bin:/usr/sbin:/usr/bin
NAME=restore-frontend
DESC="RESTORE"
PIDDIR=/var/run/restore
SCRIPTNAME=/etc/init.d/restore-frontend
ENV="env -i LANG=C PATH=/usr/local/bin:/usr/bin:/bin"
SSD="/sbin/start-stop-daemon"

PUSH_SERVER="/usr/share/restore-frontend/script/push_server"
PUSH_SERVER_OPTS="start"
PUSH_SERVER_PIDFILE=/var/run/restore/restore_push.pid

test -x $PUSH_SERVER || exit 0

set -e

. /lib/lsb/init-functions

case "$1" in
  start)
	if [ ! -d $PIDDIR ]; then
		mkdir -p $PIDDIR
	fi
	chown restore:restore $PIDDIR

	log_daemon_msg "Starting $DESC frontend"
	log_progress_msg "push server"
	if ! $ENV $SSD --start --quiet --pidfile $PUSH_SERVER_PIDFILE --exec $PUSH_SERVER -- $PUSH_SERVER_OPTS; then
		log_end_msg 1
	else
		log_end_msg 0
	fi

    	;;
  stop)
	log_daemon_msg "Stopping $DESC frontend"
	log_progress_msg "push server"
	if $SSD --quiet --stop --oknodo --retry 30 --pidfile $PUSH_SERVER_PIDFILE; then
		rm -f $PUSH_SERVER_PIDFILE
	fi
	log_end_msg 0
	;;
  restart|force-reload)
	$0 stop
	$0 start
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
