#!/bin/sh -e


. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/postrm
dbc_go restore-dc-common $@


case "$1" in
    purge|remove)
        if [ "$1" = "purge" ]; then
                rm -f /etc/restore/database.yml
                if which ucf >/dev/null 2>&1; then
                        ucf --purge /etc/restore/database.yml
                fi
                db_purge || true
        fi

    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d restore-backend remove >/dev/null || exit $?
fi
# End automatically added section


exit 0
