#!/bin/sh

. /usr/share/debconf/confmodule

# Automatically added by dh_installinit
if [ -x "/etc/init.d/restore-backend" ]; then
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d restore-backend stop || exit $?
	else
		/etc/init.d/restore-backend stop || exit $?
	fi
fi
# End automatically added section

. /usr/share/dbconfig-common/dpkg/prerm
dbc_go restore-dc-common $@


exit 0
