#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/restore-frontend" ]; then
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d restore-frontend stop || exit $?
	else
		/etc/init.d/restore-frontend stop || exit $?
	fi
fi
# End automatically added section
